// Capture a hub thumbnail from the running game (#124).
//
//   npm run thumbnail -- tower-stacker
//   npm run thumbnail                    # every game that has a pose hook
//
// There was no committed way to do this. The two 3D thumbnails were made by an
// ad-hoc Playwright script written in the session that added them and deleted
// at commit time, because a throwaway file at the repo root is worse than
// none — so the knowledge shipped and the tool did not, and the next game
// would have re-derived it. This is that tool.
//
// The part that cannot be generic is getting the game somewhere worth
// photographing: a title screen is rarely the best card. So each game owns a
// `thumbnail.mjs` beside it exporting `pose(page)`, which drives its own
// `window.__game` handle however it needs to. The tool owns everything else.
import { readdirSync, writeFileSync, existsSync } from 'node:fs'
import { chromium } from 'playwright-core'
import { ROOT, browserLaunchOptions, startDevServer } from '../qa/harness.mjs'
import { IMAGE_DIR, declaredSize } from '../qa/thumbnails.mjs'

/**
 * A game is a directory with both a page to load and a pose hook to run.
 *
 * Both halves matter. Testing only for `thumbnail.mjs` matched `scripts/`,
 * because this file *is* a `scripts/thumbnail.mjs` — so the tool's first act
 * was to navigate to `/games/scripts/`, get the dev server's SPA fallback, and
 * wait thirty seconds for a canvas that was never going to exist. Requiring an
 * `index.html` says what a game actually is instead of pattern-matching a
 * filename.
 */
function isGame(name) {
  return existsSync(`${ROOT}${name}/index.html`) && existsSync(`${ROOT}${name}/thumbnail.mjs`)
}

function gamesWithHooks() {
  return readdirSync(ROOT, { withFileTypes: true })
    .filter((e) => e.isDirectory() && !e.name.startsWith('.') && e.name !== 'node_modules')
    .map((e) => e.name)
    .filter(isGame)
    .sort()
}

/**
 * How the game's canvas becomes a thumbnail.
 *
 * This function is the house treatment, and it is deliberately the only place
 * that decides anything about how a thumbnail looks. **#123 has not settled
 * what that treatment should be** — when it does, it replaces the body of this
 * function and every card is regenerated by re-running the tool.
 *
 * What it does today is what the existing thumbnails already are: fill the
 * card's box, integer-scaled and unsmoothed when the source is small enough to
 * be pixel art, so a 160x144 game keeps hard 4x4 pixels instead of a blurred
 * upscale. Top-aligned rather than centre-cropped, because these games put
 * their score line along the top and centring cuts it off.
 */
/**
 * The viewport a game is photographed at.
 *
 * Per-game like the pose, and for the same reason. The GameBoy pages want a
 * tall window, because their pre-init script sizes the console from the
 * available height. A standalone game fills whatever it is given, so a
 * portrait window hands the treatment a portrait frame and most of the board
 * is cropped away reaching the card's shape. A game may export `viewport` from
 * its `thumbnail.mjs` to say so.
 */
const DEFAULT_VIEWPORT = { width: 520, height: 900 }

async function capture(game, page, baseUrl, size) {
  const hook = await import(`${ROOT}${game}/thumbnail.mjs`)
  const { pose, viewport = DEFAULT_VIEWPORT } = hook
  await page.setViewportSize(viewport)

  const url = new URL(`${game}/`, baseUrl)
  url.searchParams.set('qa', '1')
  await page.goto(url.toString(), { waitUntil: 'load' })
  await page.waitForSelector('#game canvas, canvas', { timeout: 20_000 })
  await page.waitForTimeout(1500)

  await pose(page)

  // ---------------------------------------------------------- the treatment
  //
  // This callback is the house treatment, and deliberately the only place that
  // decides anything about how a thumbnail looks. **#123 has not settled what
  // that treatment should be** — when it does, it replaces the body of this
  // function and every card is regenerated by re-running the tool.
  //
  // What it does today is what the existing thumbnails already are: fill the
  // card's box, integer-scaled and unsmoothed when the source is small enough
  // to be pixel art, so a 160x144 game keeps hard 4x4 pixels instead of a
  // blurred upscale. Top-aligned rather than centre-cropped, because these
  // games put their score line along the top and centring cuts it off.
  //
  // It has to be written inline rather than passed in as a named function:
  // Playwright serialises the callback itself, so it cannot call anything from
  // this module's scope, and the obvious workaround — passing the source and
  // `eval`-ing it in the page — is blocked by the games' own CSP, which is
  // `script-src 'self'` plus a hash and no `unsafe-eval`.
  const dataUrl = await page.evaluate(
    ([W, H]) => {
      const source = document.querySelector('#game canvas') ?? document.querySelector('canvas')
      const out = document.createElement('canvas')
      out.width = W
      out.height = H
      const ctx = out.getContext('2d')
      const sw = source.width
      const sh = source.height
      // "Pixel art" means a backing store small enough that every source pixel
      // is meant to be seen as one. 320 is two GameBoy screens wide; anything
      // above it is a full-resolution render that should be filtered.
      const pixelArt = sw <= 320
      ctx.imageSmoothingEnabled = !pixelArt
      let scale = Math.max(W / sw, H / sh)
      if (pixelArt) scale = Math.max(1, Math.ceil(scale))
      ctx.drawImage(source, 0, 0, sw, sh, 0, 0, Math.round(sw * scale), Math.round(sh * scale))
      return out.toDataURL('image/webp', 0.92)
    },
    [size.width, size.height],
  )
  const buf = Buffer.from(dataUrl.split(',')[1], 'base64')
  const out = `${ROOT}${IMAGE_DIR}/${game}.webp`
  writeFileSync(out, buf)
  return { out, bytes: buf.length }
}

const requested = process.argv.slice(2).filter((a) => !a.startsWith('-'))
const games = requested.length ? requested : gamesWithHooks()

const size = declaredSize()
if (!size) {
  console.error('could not read the thumbnail size from src/App.tsx')
  process.exit(1)
}

for (const game of games) {
  if (!existsSync(`${ROOT}${game}/index.html`)) {
    console.error(`${game}: no index.html — is that a game directory?`)
    process.exit(1)
  }
  if (!existsSync(`${ROOT}${game}/thumbnail.mjs`)) {
    console.error(`${game}: no thumbnail.mjs — it needs one exporting \`pose(page)\`,`)
    console.error('       which drives the game to a frame worth photographing.')
    process.exit(1)
  }
}

const server = await startDevServer({ port: process.env.QA_PORT ?? '5179' })
let browser
let failed = 0
try {
  browser = await chromium.launch(browserLaunchOptions())
  const context = await browser.newContext({ viewport: DEFAULT_VIEWPORT })
  const page = await context.newPage()
  const errors = []
  page.on('pageerror', (e) => errors.push(String(e.message)))

  console.log(`capturing at ${size.width}x${size.height}\n`)
  for (const game of games) {
    errors.length = 0
    const { out, bytes } = await capture(game, page, server.url, size)
    // A game that threw on the way to its pose has produced a picture of a
    // broken game, and a silently wrong thumbnail is worse than none.
    if (errors.length) {
      console.error(`  FAIL ${game} — page errors: ${errors.join('; ')}`)
      failed++
      continue
    }
    console.log(`  ok   ${game} -> ${out.replace(ROOT, '')} (${Math.round(bytes / 1024)} kB)`)
  }
} finally {
  await browser?.close()
  server.stop()
}

if (failed) {
  console.error('\nsome captures failed')
  process.exit(1)
}
console.log('\nRun `npm run qa:units` to check the results against what App.tsx declares.')
